modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://github.com/DAQEM/Arc/issues"
license = "MIT"

[[mods]]
modId = "arc"
version = "${version}"
displayName = "Arc"
authors = "DAQEM"
logoFile = "icon.png"
description = '''

'''
#logoFile = ""

[[dependencies.arc]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arc]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arc]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.arc]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.arc]]
modId = "uilib"
mandatory = true
versionRange = "[${ui_library_version},)"
ordering = "NONE"
side = "CLIENT"